---
- name: AS3 http setup 
  hosts: "{{ target }}"
  connection: local
  gather_facts: false
  vars:
    AS3Version: "3.19.0-4"
    provider:
      server: "{{ private_ip }}"
      server_port: "8443"
      user: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      validate_certs: "no"

  tasks:

  - name: Manage AS3 externsion version {{ AS3Version }}
    bigip_lx_package:
      provider: "{{ provider }}"
      package: "files/f5-appsvcs-{{ AS3Version }}.noarch.rpm"

...    
